[env:adafruit_feather_esp32_v2]
platform = https://github.com/pioarduino/platform-espressif32.git
board = adafruit_feather_esp32c6
framework = arduino
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
upload_protocol = esptool
upload_port = COM19
monitor_port = COM19
build_flags =
  -DSDL_SENSOR_AS7343=1
lib_deps =
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit AS7343
  adafruit/Adafruit BusIO
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer

[env:adafruit_feather_esp32_v2_as7341]
platform = https://github.com/pioarduino/platform-espressif32.git
board = adafruit_feather_esp32c6
framework = arduino
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
upload_protocol = esptool
upload_port = COM19
monitor_port = COM19
build_flags =
  -DSDL_SENSOR_AS7341=1
lib_deps =
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit AS7341
  adafruit/Adafruit BusIO
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
