[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_port = COM14
monitor_port = COM14
build_flags =
  -DSDL_SENSOR_AS7343=1
lib_deps =
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit AS7343
  adafruit/Adafruit BusIO
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer

[env:adafruit_feather_esp32_v2_as7341]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_port = COM14
monitor_port = COM14
build_flags =
  -DSDL_SENSOR_AS7341=1
lib_deps =
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit AS7341
  adafruit/Adafruit BusIO
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
